### ISSUE TITLE
v0.2 Roadmap

### ISSUE THREAD

**Issue by IridescentRose** [NT-Bourgeois-Iridescence-Technologies/PSP-Craft-Server#1]
Goal: Load up basic chunks and send them to the client - requires other pre-setup packets too.

- [x] Add Necessary Game Packets to be sent as a startup bundle
- [x] Create NBT library (or find one)
- [x] Create a block/chunk system for ANVIL format
- [x] Send chunk data as packets
- [x] Add any other necessary formatting choices
- [x] Break and Place blocks!

**Comment by IridescentRose** [comment]
Also need to make infinite terrain again (easy) and unload shit.
