### ISSUE TITLE
v0.3 Checklist

### ISSUE THREAD

**Issue by IridescentRose** [NT-Bourgeois-Iridescence-Technologies/PSP-Craft-Server#6]
- [x] Inventory management support
- [x] Add All Items
- [x] Placing item removes item from inventory
- [x] Chunk saving (easy)
- [x] Inventory Saving (easy)
- [x] Add All Blocks (block data & loot)
- [x] Placing items into the world (chunks & block data)
- [x] Breaking yields item drops (block data & loot & entity)
- [x] Item drops go into inventory (entity delete & inventory)
- [ ] Inventory management
- [ ] Crafting (craft & recipes)
- [ ] Loot table / Craft table loading (craft & loot & block data)
